name: Build

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: gradle build

      - name: Archive Jar Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.jar
          path: build/libs/filter-1.0-all.jar
          retention-days: 1